### ISSUE TITLE
Can't run the workspace

### ISSUE THREAD

**Issue by RadityaFiqa** [sirhypernova/c9launcher#1]
i have complete all instalation and creat new workspace but i can't run the workspace

**Comment by RadityaFiqa** [comment]
http://prntscr.com/n02hzw
http://prntscr.com/n02ihr

**Comment by sirhypernova** [comment]
There could be 2 different things going on here. First, make sure you have properly installed the cloud9sdk. This includes running the install script (this is the most likely cause of your issue).
The other problem may have been that you did not include the proper path in the config. Make sure the path is to the directory that contains all the cloud9 scripts. For example, if the script itself was `~/c9sdk/server.js`, your path should be `~/c9sdk`.

**Comment by RadityaFiqa** [comment]
i have installed the cloud9sdk 
check this out http://prntscr.com/n032nu

**Comment by sirhypernova** [comment]
You have installed it to /root/c9launcher/c9sdk
Change that in your config to /root/c9launcher/c9sdk

**Comment by RadityaFiqa** [comment]
i have change the path config , but i got error , and what is the mean of crypto in config ?
https://prnt.sc/n03p2o
i'm sorry i'm bad in english

**Comment by sirhypernova** [comment]
Crypto is the key used for encrypt the passwords that you use when you launch instances of cloud9.
If cryptr is giving you issues, try checking your nodejs version. I created this in NodeJS v8.

**Comment by RadityaFiqa** [comment]
i'm using nodeJS v8.15.1,please check this one again , and thank you before 👍 
http://prntscr.com/n041nb

**Comment by RadityaFiqa** [comment]
Solved , Thank you !!!

**Comment by sirhypernova** [comment]
Glad you fixed it. Crypto should be any random string of characters, but it cannot be changed after you create a workspace.
